print('Hoje vamos descobrir sua altura em cm e mm')
altura = float(input('Qual sua altura em metro? = '))
altkm = float(altura / 1000)
althm = float(altura / 100)
altdam = float(altura / 10)
altdm = int(altura * 10)
altcm = int(altura * 100)
altmm = int(altura * 1000)
print('você tem {} m/cm de altura. em cm é {:.0f}cm, em milimetros {:.0f}mm'. format(altura, altcm, altmm))
print('Em {}dm fica'. format(altdm))
print('Em {}dam'.format(altdam))
print('Em {}hm'.format(althm))
print('Em {}km'.format(altkm))
